title: Jeet Arvindkumar Swami
logo: /Images/JEET SWAMI.png
description: <p style="text-align: justify;"> Experienced Data Analyst with expertise in data modeling, ETL processes, and business intelligence tools like Tableau and SQL. Skilled in analyzing large datasets, creating actionable reports, and collaborating with stakeholders to deliver insights. Proficient in Python, Microsoft Office, and effective communication in fast-paced environments. </p>
show_downloads: false
theme: jekyll-theme-minimal
